nodeLinker: node-modules
enableGlobalCache: true
enableConstraintsChecks: true
injectEnvironmentFiles:
  - ".env?"
npmScopes:
  "ds-fancode":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${GH_TOKEN}
